language: java
jdk:
  - oraclejdk7
  
env:
  global:
   - secure: "XsNksW66VFNSPOwEekFWPJzsau0Hsn84LcoG4hdBXbnuUjPXnogQQw+h77uNfnsfZUcDsx5DV6Kzr7F492UTrw2BMf+VaheF9aE5oSOMRqu0KWo5ODbfFnlFKQbTiVtCDaCTFQWqVzOMAVIXL7kTBQw+Vn0Mv4OOi2q9A9CRKAQ="

addons:
  coverity_scan:
    project:
      name: "atomfrede/freezing-octo-bear"
      description: "Your project description here"
    notification_email: atomfrede@gmail.com
    build_command_prepend: "cov-configure --java"
    build_command: "cov-build --dir cov-int mvn clean compile"
    branch_pattern: coverity_scan

after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura

