language: java
jdk:
  - oraclejdk8
  
env:
  global:
   - secure: "XsNksW66VFNSPOwEekFWPJzsau0Hsn84LcoG4hdBXbnuUjPXnogQQw+h77uNfnsfZUcDsx5DV6Kzr7F492UTrw2BMf+VaheF9aE5oSOMRqu0KWo5ODbfFnlFKQbTiVtCDaCTFQWqVzOMAVIXL7kTBQw+Vn0Mv4OOi2q9A9CRKAQ="

script: mvn --quiet install -DskipTests=true -Dmaven.javadoc.skip=true -Dorg.slf4j.simpleLogger.defaultLogLevel=error -B -V
addons:
  coverity_scan:
    project:
      name: "atomfrede/freezing-octo-bear"
      description: "Your project description here"
    notification_email: atomfrede@gmail.com
    build_command_prepend: 
    build_command: mvn clean install -DskipTests
    branch_pattern: coverity_scan

after_success:
  - mvn --quiet clean cobertura:cobertura coveralls:cobertura -Dorg.slf4j.simpleLogger.defaultLogLevel=error

